export const HELP_COMMANDS: [string, string][] = [
  ["/help, /h", "Show this help message"],
  ["/clear, /c", "Clear conversation history"],
  ["/files, /f", "List files in context"],
  ["/remove <file>, /rm", "Remove file from context"],
  ["/context", "Show current context size"],
  ["/compact", "Compact conversation history"],
  ["/history", "Show conversation history"],
  ["/models, /m", "Show available models"],
  ["/model <name>", "Switch to a different model"],
  ["/providers, /p", "Show all providers status"],
  ["/provider <name>", "Switch to a different provider"],
  ["/agent, /a", "Select agent"],
  ["/usage, /u", "Show token usage statistics"],
  ["/mcp [cmd]", "MCP server status/connect/disconnect/tools"],
  ["/session", "Show current session info"],
  ["/sessions", "List all saved sessions"],
  ["/save, /s", "Save current session"],
  ["/exit, /quit, /q", "Exit chat"],
];
